#!/bin/sh

git checkout locale conf.py $(find -name "*.rst")

sed -i conf.py -e "s/'Veyon'/'M@school Veyon'/g"
sed -i conf.py -e "s/school Veyon-/school Veyon /g"

for i in locale/de/LC_MESSAGES/*.po ; do
    sed -i $i -e "s/Veyon/M\\\\\\\\@school Veyon/g"
	sed -i $i -e "s/school Veyon-/school Veyon /g"
done

for i in $(find -name "*.rst") ; do
    sed -i $i -e "s/:scale: 20%/:scale: 75%/g"
    sed -i $i -e "s/Veyon/M\\\\@school Veyon/g"
	sed -i $i -e "s/school Veyon-/school Veyon /g"
done

make gettext

./create-user-manual-de.py

pdftk ~/LHM/Handbücher/Deckblatt_M@School-Veyon_Benutzerhandbuch-4.4.3.pdf cat 2 output /tmp/2.pdf
pdftk ~/LHM/Handbücher/Deckblatt_M@School-Veyon_Benutzerhandbuch-4.4.3-LHMS-Kontaktdaten.pdf cat 3 output /tmp/3.pdf
pdftk ~/LHM/Handbücher/Deckblatt_M@School-Veyon_Benutzerhandbuch-LHMS-4.4.3.pdf /tmp/2.pdf /tmp/3.pdf cat output /tmp/deckblatt-lhms.pdf

pdftk ~/LHM/Handbücher/Deckblatt_M@School-Veyon_Benutzerhandbuch-4.4.3.pdf veyon-user-manual-de_*.pdf cat output M@school-Veyon_Benutzerhandbuch_V.4.4.3.pdf
pdftk /tmp/deckblatt-lhms.pdf veyon-user-manual-de_*.pdf cat output M@school-Veyon_Benutzerhandbuch-LHMS_V.4.4.3.pdf

